Rent/Rent/Models/RentLocation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class RentLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentLocation()
        {
            this.Order = new HashSet<Order>();
        }
        [DisplayName("取車編號")]
        public string rentID { get; set; }
        [DisplayName("取車門市")]
        public string rentLocation1 { get; set; }
        [DisplayName("門市地址")]
        public string rentAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}

Rent/Rent/Controllers/RentlocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Rent.Models;
namespace Rent.Controllers
{
    public class RentlocationController : Controller
    {
        // GET: Rentlocation
        // GET: RentLocation
        rentEntities db = new rentEntities();
        public ActionResult BIndex(string searchString)
        {
            var brands = db.RentLocation.ToList();
            if (!string.IsNullOrEmpty(searchString))
            {
                // 使用 Contains 方法進行模糊搜尋，你可以根據實際需求調整查詢條件
                brands = brands.Where(c => c.rentID.Contains(searchString)).ToList();
            }
            return View(brands);
        }

        public ActionResult BCreate()
        {
            return View();
        }

        [HttpPost]

        public ActionResult BCreate(RentLocation brands)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Error = false;
                var temp = db.RentLocation.Where(m => m.rentID == brands.rentID).FirstOrDefault();
                if (temp != null)
                {
                    ViewBag.Error = true;
                    return View(brands);
                }
                db.RentLocation.Add(brands);
                db.SaveChanges();
                return RedirectToAction("BIndex");
            }
            return View(brands);
        }
        public ActionResult BEdit(string rentID)
        {
            var brand = db.RentLocation.Where(m => m.rentID == rentID).FirstOrDefault();
            db.Dispose();
            return View(brand);
        }

        [HttpPost]

        public ActionResult BEdit
            (string rentID, string rentLocation1, string rentAddress)
        {
            var Temp = db.RentLocation.Where(m => m.rentID == rentID).FirstOrDefault();
            Temp.rentID = rentID;
            Temp.rentLocation1 = rentLocation1;
            Temp.rentAddress = rentAddress;
            db.SaveChanges();
            return RedirectToAction("BIndex");
        }
        public ActionResult BDelete(string id)
        {
            var brands = db.RentLocation.Where(m => m.rentID == id).FirstOrDefault();
            db.RentLocation.Remove(brands);
            db.SaveChanges();
            return RedirectToAction("BIndex");
        }
    }
}

Rent/Rent/Views/Rentlocation/BCreate.cshtml
@model Rent.Models.RentLocation

@{
    ViewBag.Title = "建立地點";
}

<h2>建立地點</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.rentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rentLocation1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rentLocation1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rentLocation1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到地點", "BIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rent/Rent/Views/Rentlocation/BEdit.cshtml
@model Rent.Models.RentLocation

@{
    ViewBag.Title = "地點編輯";
}

<h2>地點編輯</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.rentID)

        <div class="form-group">
            @Html.LabelFor(model => model.rentLocation1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rentLocation1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rentLocation1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到地點", "BIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rent/Rent/Views/Rentlocation/BIndex.cshtml
@model IEnumerable<Rent.Models.RentLocation>

@{
    ViewBag.Title = "租車地點";
}

<h2>租車地點</h2>

<p>
    @Html.ActionLink("建立地點", "BCreate")
</p>
@using (Html.BeginForm("BIndex", "Rentlocation", FormMethod.Get))
{
    <p>
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { placeholder = "Search" })
        <input type="submit" value="搜尋" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.rentLocation1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rentAddress)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.rentLocation1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rentAddress)
            </td>
            <td>
                @Html.ActionLink("編輯", "BEdit", new { rentID = item.rentID }) |

                @Html.ActionLink("刪除", "BDelete", new { rentID = item.rentID }, new { onclick = "return confirm('確定要刪除嗎')" })
            </td>
        </tr>
    }

</table>